name: Build repo

on:
  workflow_dispatch:

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
      - run: python3 --version
      - uses: actions/checkout@v2